# Generated by Django 4.2.16 on 2026-06-08 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('manual', '직접입력'), ('csv', 'CSV 업로드'), ('api', 'API 연동')], default='manual', max_length=20)),
                ('food_monthly', models.PositiveIntegerField(default=0, verbose_name='식비(원/월)')),
                ('transport_monthly', models.PositiveIntegerField(default=0, verbose_name='교통비(원/월)')),
                ('shopping_monthly', models.PositiveIntegerField(default=0, verbose_name='쇼핑비(원/월)')),
                ('entertainment_monthly', models.PositiveIntegerField(default=0, verbose_name='여가비(원/월)')),
                ('communication_monthly', models.PositiveIntegerField(default=0, verbose_name='통신비(원/월)')),
                ('other_monthly', models.PositiveIntegerField(default=0, verbose_name='기타(원/월)')),
                ('age_group', models.CharField(choices=[('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대'), ('60s', '60대 이상')], max_length=10, verbose_name='연령대')),
                ('max_annual_fee', models.PositiveIntegerField(default=0, verbose_name='최대 연회비(원)')),
                ('income_level', models.CharField(choices=[('low', '저소득'), ('mid', '중소득'), ('high', '고소득')], max_length=10, verbose_name='소득 수준')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '지출 설문',
                'verbose_name_plural': '지출 설문 목록',
                'db_table': 'surveys_usersurvey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', '식비'), ('transport', '교통'), ('shopping', '쇼핑'), ('entertainment', '여가'), ('communication', '통신'), ('health', '의료/건강'), ('other', '기타')], max_length=50, verbose_name='카테고리')),
                ('merchant', models.CharField(max_length=200, verbose_name='가맹점')),
                ('amount', models.IntegerField(verbose_name='금액(원)')),
                ('transaction_date', models.DateField(verbose_name='거래일')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='surveys.usersurvey')),
            ],
            options={
                'verbose_name': '지출 거래내역',
                'verbose_name_plural': '지출 거래내역 목록',
                'db_table': 'surveys_spendingtransaction',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
