# Generated by Django 4.2.16 on 2026-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='fuel_monthly',
            field=models.PositiveIntegerField(default=0, verbose_name='주유비(원/월)'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='health_monthly',
            field=models.PositiveIntegerField(default=0, verbose_name='의료/건강비(원/월)'),
        ),
    ]
