# Generated by Django 4.2.16 on 2026-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_usersurvey_fuel_monthly_usersurvey_health_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingtransaction',
            name='category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통'), ('fuel', '주유'), ('shopping', '쇼핑'), ('entertainment', '여가'), ('communication', '통신'), ('health', '의료/건강'), ('other', '기타')], max_length=50, verbose_name='카테고리'),
        ),
    ]
