# Generated by Django 4.2.16 on 2026-06-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_company', models.CharField(max_length=100, verbose_name='카드사')),
                ('card_name', models.CharField(max_length=200, verbose_name='카드명')),
                ('card_type', models.CharField(choices=[('credit', '신용카드'), ('debit', '체크카드'), ('prepaid', '선불카드')], max_length=20, verbose_name='카드 종류')),
                ('annual_fee', models.PositiveIntegerField(default=0, verbose_name='연회비(원)')),
                ('min_prev_month_spending', models.PositiveIntegerField(default=0, verbose_name='전월 실적 기준(원)')),
                ('apply_url', models.URLField(blank=True, verbose_name='신청 URL')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': '카드',
                'verbose_name_plural': '카드 목록',
                'db_table': 'cards_card',
                'ordering': ['card_company', 'card_name'],
            },
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_category', models.CharField(choices=[('food', '식비'), ('transport', '교통'), ('shopping', '쇼핑'), ('entertainment', '여가/문화'), ('communication', '통신'), ('travel', '여행'), ('health', '의료/건강'), ('other', '기타')], max_length=50, verbose_name='혜택 카테고리')),
                ('benefit_type', models.CharField(choices=[('discount', '할인'), ('cashback', '캐시백'), ('point', '포인트 적립'), ('mileage', '마일리지')], max_length=20, verbose_name='혜택 유형')),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='할인/적립률(%)')),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='월 한도(원)')),
                ('condition_description', models.TextField(blank=True, verbose_name='조건 설명')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='cards.card')),
            ],
            options={
                'verbose_name': '카드 혜택',
                'verbose_name_plural': '카드 혜택 목록',
                'db_table': 'cards_cardbenefit',
            },
        ),
    ]
