# Generated by Django 4.2.16 on 2026-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='카드 이미지 URL'),
        ),
    ]
