# Generated by Django 4.2.16 on 2026-06-22 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_card_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('search', '검색'), ('detail', '상세'), ('recommendation', '추천'), ('compare', '비교')], default='search', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_wish_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜 카드',
                'verbose_name_plural': '찜 카드 목록',
                'db_table': 'card_wish_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cardwishlist',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='unique_user_card_wish'),
        ),
    ]
