# Generated by Django 4.2.16 on 2026-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardwishlist_cardwishlist_unique_user_card_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbenefit',
            name='benefit_category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통'), ('fuel', '주유'), ('shopping', '쇼핑'), ('entertainment', '여가/문화'), ('communication', '통신'), ('travel', '여행'), ('health', '의료/건강'), ('other', '기타')], max_length=50, verbose_name='혜택 카테고리'),
        ),
    ]
